<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<small class="copyright">
    <span>© 2018 Burning Log. All rights reserved</span>
    <span class="right">
        <ul>
            <li><a href=""><img src="http://127.0.0.1/magento/pub/media/wysiwyg/eway.png" alt=""></a></li>
            <li><a href=""><img src="http://127.0.0.1/magento/pub/media/wysiwyg/paypal.png" alt=""></a></li>
            <li><a href=""><img src="http://127.0.0.1/magento/pub/media/wysiwyg/visa.png" alt=""></a></li>
            <li><a href=""><img src="http://127.0.0.1/magento/pub/media/wysiwyg/mastercard.png" alt=""></a></li>
            <li><a href=""><img src="http://127.0.0.1/magento/pub/media/wysiwyg/express.png" alt=""></a></li>
        </ul>
    </span>
</small>
