<div class="header-top-desktop-left">
    <?php echo
        $block->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('header-top-left-contact-phone')
            ->toHtml(); ?>
</div>
<div class="header-top-desktop-center">
    <?php echo
    $block->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('header-top-center-link')
        ->toHtml(); ?>
</div>
<div class="header-top-desktop-right">
    <?php echo
    $block->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('header-top-right-infor')
        ->toHtml(); ?>
</div>
<div class="header-top-mobile-left">
    <?php echo
    $block->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('header-top-left-mobile-address')
        ->toHtml(); ?>
</div>
<div class="header-top-mobile-right">
    <?php echo
    $block->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('header-top-right-mobile-phone-contact')
        ->toHtml(); ?>
</div>
