<!--Home main content-->
<div class="home-main-content ">
<?php for($i=1;$i<3;$i++): ?>
    <div class="row">
        <div class="col">
            <div class="desktop"><?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home_content_'.$i.'')->toHtml(); ?></div>
            <div class="mobile"><?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home_content_'.$i.'_mobile')->toHtml(); ?></div>
            <div class="col-content icon-next">
                <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home_content_'.$i.'_detail')->toHtml(); ?>
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home_content_link')->toHtml(); ?>
            </div>
        </div>
    </div>
<?php endfor; ?>
</div>

<!--Home main link-->
<div class="home-main-link owl-carousel owl-theme">
    <?php for($i=1;$i<4;$i++): ?>
    <div class="item">
        <div <?php echo "class='icon-next caro_$i'";?> ><?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('caro_link_'.$i.'')->toHtml(); ?></div>
    </div>
    <?php endfor; ?>
</div>
<script type="text/javascript" xml="space">
    require([
        'jquery',
        'owlcarousel'
    ], function($){
        $(document).ready(function() {
            $('.owl-carousel ').owlCarousel({
                loop:true,
                nav:false,
                dots:false,
                items : 1, // THIS IS IMPORTANT
                responsive : {
                    480 : { items : 1  }, // from zero to 480 screen width 4 items
                    768 : { items : 2  }, // from 480 screen widthto 768 6 items
                    1024 : { items : 3, loop:false,   // from 768 screen width to 1024 8 items
                    }
                },

                autoplay:false,
                autoplayTimeout:3000
            })
        });
    });
</script>

<!--Home three-->
<div class="home-three-title">
    <?php for($i=1;$i<4;$i++): ?>
    <div class="row">
        <div class="col">
            <div class="desktop">
                <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home_three_'.$i.'')->toHtml(); ?>
            </div>
            <div class="mobile">
                <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home_three_'.$i.'_mobile')->toHtml(); ?>

            </div>
            <div class="home-three-content">
                <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home_three_content_'.$i.'')->toHtml(); ?>
                <div class="col-content icon-next">
                    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home_three_link')->toHtml(); ?>
                </div>
            </div>
        </div>
    </div>
    <?php endfor;?>
</div>

<!--Content 3-->
<div class="home-main-content content-3">
    <?php for($i=3;$i<5;$i++): ?>
        <div class="row">
            <div class="col">
                <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home_content_'.$i.'')->toHtml(); ?>
                <div class="col-content icon-next">
                    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home_content_'.$i.'_detail')->toHtml(); ?>
                    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home_content_'.$i.'_link')->toHtml(); ?>
                </div>
            </div>
        </div>
    <?php endfor; ?>
</div>

<!--Best sellers-->
<div class="best-sellers">
    <div class="home-title">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('best_sellers_title')->toHtml(); ?>
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('best_sellers_title')->toHtml(); ?>

    </div>
    <div class="best-sellers-slick">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('best_sellers')->toHtml(); ?>

    </div>
</div>

<!--New arrivals-->
<div class="new-arrivals">
    <div class="home-title">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('new_arrivals_title')->toHtml(); ?>
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('new_arrivals_title')->toHtml(); ?>

    </div>
    <div class="new_arrivals-slick">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('new_arrivals')->toHtml(); ?>

    </div>
</div>

<script>
    require([
        'jquery',
        'slick'
    ], function ($) {
        $(document).ready(function () {
            $(".product-items").slick({
                dots: false,
                infinite: true,
                speed: 300,
                slidesToShow: 4,
                slidesToScroll: 4,
                autoplay: false,
                autoplaySpeed: 2000,
                arrows: true,
                responsive: [
                    {
                        breakpoint: 780,
                        settings: {
                            slidesToShow: 4,
                            slidesToScroll: 4,
                            infinite: true,
                            arrows: false,
                            dots: false
                        }
                    },
                    {
                        breakpoint: 640,
                        settings: {
                            slidesToShow: 2,
                            slidesToScroll: 3,
                            rows: 2,
                            infinite: true,
                            arrows: false,
                            dots: false
                        }
                    },
                ]
            });
        });
    });
</script>

<!--Instagram-->
<div class="instagram">
    <div class="insta-title home-title">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('instagram_block_title')->toHtml(); ?>
    </div>
    <div class="insta-slick">

        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('instagram_block_content')->toHtml(); ?>
    </div>
    <div class="insta-link home-view-more">
    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('instagram_block_link')->toHtml(); ?>
    </div>
</div>

<script>
    require([
        'jquery',
        'slick'
    ], function ($) {
        $(document).ready(function () {
            $(".insta-slick").slick({
                dots: false,
                infinite: true,
                speed: 300,
                slidesToShow: 5,
                slidesToScroll: 5,
                autoplay: false,
                autoplaySpeed: 2000,
                arrows: true,
                responsive: [
                    {
                        breakpoint: 780,
                        settings: {
                            slidesToShow: 3,
                            slidesToScroll: 3,
                            infinite: true,
                            arrows: false,
                            dots: true
                        }
                    },
                    {
                        breakpoint: 640,
                        settings: {
                            slidesToShow: 2,
                            slidesToScroll: 3,
                            rows: 2,
                            infinite: true,
                            arrows: false,
                            dots: true
                        }
                    },
                ]
            });
        });
    });
</script>

<!--Our Blog-->
<div class="our-blog">
    <div class="home-title">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home_blog_title')->toHtml(); ?>
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home_blog_title')->toHtml(); ?>
    </div>
    <div class="blog">
    <?php for($i=1;$i<7;$i++): ?>
    <div class="blog-content">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home_blog_'.$i.'')->toHtml(); ?>
    </div>
    <?php endfor;?>
    </div>
</div>

<!--Home testi-->
<div class="home-testi">
    <div class="home-title">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home_testi_title')->toHtml(); ?>
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home_testi_title')->toHtml(); ?>
    </div>
    <div class="testi">
        <?php for($i=1;$i<5;$i++): ?>
        <div class="testi-content">
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home_testi_'.$i.'')->toHtml(); ?>
        </div>
        <?php endfor; ?>
    </div>
    <div class="testi-link home-view-more">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home_testi_link')->toHtml(); ?>
    </div>
</div>
