
<div class="u-may-so-like">
    <div class="title">
        <h3>You may so like</h3>
    </div>

    <div class="list">

                <div class="item">
                    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('popup_main_image')->toHtml(); ?>
                    <p class="more">more colours available</p>
                    <p class="title"><h4>Maldives Sunbrella 3pc Outdoor Modular Sofa Setting - Moonscape/ Canvas Coal</h4></p>
                    <p class="price">$2,495.00</p>
                    <p><button class="standard-button" type="button">add to cart</button></p>
                </div>
                <div class="item">
                    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('popup_main_image')->toHtml(); ?>
                    <p class="more">more colours available</p>
                    <p class="title"><h4>Maldives Sunbrella 5pc Outdoor Modular Sofa Setting - Moonscape/ Canvas Coal</h4></p>
                    <p class="price">$2,495.00</p>
                    <p><button class="standard-button" type="button">add to cart</button></p>
                </div>
                <div class="item">
                    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('popup_main_image')->toHtml(); ?>
                    <p class="more">more colours available</p>
                    <p class="title"><h4>Maldives Sunbrella 6pc Outdoor Modular Sofa Setting - Moonscape/ Canvas Coal</h4></p>
                    <p class="price">$2,495.00</p>
                    <p><button class="standard-button" type="button">add to cart</button></p>
                </div>
                <div class="item">
                    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('popup_main_image')->toHtml(); ?>
                    <p class="more">more colours available</p>
                    <p class="title"><h4>Maldives Sunbrella 6pc Outdoor Modular Sofa Setting - Moonscape/ Canvas Coal</h4></p>
                    <p class="price">$2,495.00 <span>$1,295.00</span></p>
                    <p><button class="standard-button" type="button">add to cart</button></p>
                </div>

    </div>
    
</div>