<!-- 
<div class="product-add-form">
    <form action="#">
        <input type="hidden" name="product" value>
        <input type="hidden" name="select_config_option" value>

        <div class="box-to-cart">
            <div class="fieldset">
                
                <div class="adjust-button">
                    <button class="button-adjust" type="button">-</button> 
                    <input class="input-adjust" type="number" value="1"> 
                    <button class="button-adjust" type="button">+</button>
                </div> -->
            <!-- </div>
        </div>
    </form>
</div> --> 

<div class="product-options-wrapper" id="product-options-wrapper">
    <div class="fieldset" tabindex="0">
        <div class="field-color">
            <p>choose your color</p>
        </div>
    </div>
</div>

