<div class="product-options-bottom">
    <div class="box-to-cart">
        <div class="fieldset">
            <div class="adjust-button">
                <button class="button-adjust" type="button">-</button> 
                <input class="input-adjust" type="number" value="1"> 
                <button class="button-adjust" type="button">+</button>
            </div>
            <div>
                <p><button class="action primary" type="button">Add to cart</button></p>
            </div>
        </div>
    </div>
</div>
<div class="product-details">
    <div id="accordion" data-mage-init='{
            "accordion":{
                "active": [0],
                "collapsible": true,
                "openedState": "active",
                "multipleCollapsible": false
            }}'>
        <div data-role="collapsible">
            <div data-role="trigger">
                <h4>Title 1</h4>
            </div>
        </div>
        <div data-role="content">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s</div>

        <div data-role="collapsible">
            <div data-role="trigger">
                <h4>Title 2</h4>
            </div>
        </div>
        <div data-role="content"> It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</div>

        <div data-role="collapsible">
            <div data-role="trigger">
                <h4>Title 3</h4>
            </div>
        </div>
        <div data-role="content">Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.</div>
    </div>
</div>


