<div class="product-options-bottom">
    <div class="box-to-cart">
        <div class="fieldset">
            <div class="adjust-button">
                <button class="button-adjust" type="button">-</button> 
                <input class="input-adjust" type="number" value="1"> 
                <button class="button-adjust" type="button">+</button>
            </div>
            <div>
                <p><button class="action primary" id="add-to-cart" type="button">Add to cart</button></p>
            </div>
        </div>
    </div>
</div>

<div id="modal-add-to-cart">
    <div class="modal-body-content">

        <div class="img">
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('popup_main_image')->toHtml(); ?>
        </div>
        
        <div class="content">
            <p><strong>Amalfi 6 Seater Aluminium Outdoor Modular Lounge Setting</strong></p>
            <p>was added to your cart</p>
            <p><button class="action primary" id="add-to-cart" type="button">view cart and checkout</button></p>
            <p><button class="standard-button" type="button">continue shopping</button></p>
        </div>
        
        <div class="title"><h3>we also recommened</h3></div>

        <div class="related">
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('popup_main_image')->toHtml(); ?>
            <p class="title"><h4>outdoor cover</h4></p>
            <p class="price">$89.00</p>
            <p><button class="standard-button" type="button">add to cart</button></p>
        </div>
        <div class="related">
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('popup_main_image')->toHtml(); ?>
            <p class="title"><h4>outdoor cover</h4></p>
            <p class="price">$89.00</p>
            <p><button class="standard-button" type="button">add to cart</button></p>
        </div>
        <div class="related">
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('popup_main_image')->toHtml(); ?>
            <p class="title"><h4>outdoor cover</h4></p>
            <p class="price">$89.00</p>
            <p><button class="standard-button" type="button">add to cart</button></p>
        </div>
    </div>
</div>

<script type="text/javascript">
    require([
        "jquery",
        "Magento_Ui/js/modal/modal"
    ],function($, modal) {

        var options = {
            type: 'popup',
            responsive: true,
            buttons: false
        };

        var popup = modal(options, $('#modal-add-to-cart'));
        $("#add-to-cart").click(function() {
            $('#modal-add-to-cart').modal('openModal');
        });
    });
</script>


