<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Newsletter\Block\Subscribe $block */
?>
<div class="footer-middle">
    <div class="item cate">
        <?php echo
        $block->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('footer-middle-category')
            ->toHtml(); ?>
    </div>
    <div class="item ask">
        <?php echo
        $block->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('footer-middle-ask')
            ->toHtml(); ?>
    </div>
    <div class="item policy">
        <?php echo
        $block->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('footer-middle-policies')
            ->toHtml(); ?>
    </div>
    <div class="item block newsletter">
        <div class="content">
            <div class="infor">
                <?php echo
                $block->getLayout()
                    ->createBlock('Magento\Cms\Block\Block')
                    ->setBlockId('footer-middle-newsletter')
                    ->toHtml(); ?>
            </div>
            <form class="form subscribe"
                  novalidate
                  action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
                  method="post"
                  data-mage-init='{"validation": {"errorClass": "mage-error"}}'
                  id="newsletter-validate-detail">
                <div class="field newsletter">
                    <div class="control">
                        <label for="newsletter">
                            <span class="label">
                                <?= $block->escapeHtml(__('Sign Up for Our Newsletter:')) ?>
                            </span>
                            <input name="email" type="email" id="newsletter"
                                   placeholder="<?= $block->escapeHtmlAttr(__('Enter your email address')) ?>"
                                   data-mage-init='{"mage/trim-input":{}}'
                                   data-validate="{required:true, 'validate-email':true}"
                            />
                        </label>
                    </div>
                </div>
                <div class="actions">
                    <button class="action subscribe primary"
                            title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>"
                            type="submit"
                            aria-label="Subscribe">
                        <span><?= $block->escapeHtml(__('Subscribe')) ?></span>
                    </button>
                </div>
            </form>
            <div class="social">
                <?php echo
                $block->getLayout()
                    ->createBlock('Magento\Cms\Block\Block')
                    ->setBlockId('footer-middle-newsletter-social')
                    ->toHtml(); ?>
            </div>
        </div>
    </div>
</div>
