<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Newsletter\Block\Subscribe $block */
?>
<div class="footer-middle"
     id="accordion"
     data-mage-init='{
        "accordion":{
            "collapsible": true,
            "openedState": "active",
            "multipleCollapsible": true
        }
     }'
>
    <div class="item cate">
        <?php echo
        $block->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('footer-middle-category')
            ->toHtml(); ?>
    </div>
    <div class="item ask">
        <?php echo
        $block->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('footer-middle-ask')
            ->toHtml(); ?>
    </div>
    <div class="item policy">
        <?php echo
        $block->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('footer-middle-policies')
            ->toHtml(); ?>
    </div>
    <div class="item block newsletter">
        <div class="content">
            <div class="infor">
                <?php echo
                $block->getLayout()
                    ->createBlock('Magento\Cms\Block\Block')
                    ->setBlockId('footer-middle-newsletter')
                    ->toHtml(); ?>
            </div>
            <div class="form">
                <form action="">
                    <input type="text" placeholder="Enter your email address"/>
                    <button><i class="fas fa-chevron-right"></i></button>
                </form>
            </div>

            <div class="social">
                <?php echo
                $block->getLayout()
                    ->createBlock('Magento\Cms\Block\Block')
                    ->setBlockId('footer-middle-newsletter-social')
                    ->toHtml(); ?>
            </div>
        </div>
    </div>
</div>
